#! /bin/sh
#startbspwmtobar $COLOR_ACTIVE $COLOR_HASWINDOW $COLOR_NORMAL

mkfifo /tmp/bspwm-fifo
bspc subscribe report > /tmp/bspwm-fifo &
conky > /tmp/bspwm-fifo &
xtitle -sf "x:%s" > /tmp/bspwm-fifo &

bspwmtobar -l x -c W -r c --color-active $1 --color-haswindow $2 --color-normal $3 | lemonbar -p -g 1920x30 -f "DejavuSans-10"  -f "FontAwesome-11" -B "#141821" -F "#EDEDED"
